name: Sandcastle Build and Internal Test

# This test builds Sandcastle on Linux and macOS and
# then runs its internal tests to ensure basic functionality.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    uses: ./.github/workflows/build-targets-template.yml
    with:
      build-targets: 'sandcastle_exe'
      test-targets: 'run_sandcastle_tests'
      artifact-name: 'kanagawa-linux-sandcastle-${{ github.sha }}'
      artifact-path: 'build-ci/dist/**'
      cmake-build-type: 'RelWithDebInfo'
      runs-on: 'ubuntu-24.04'
      boost-platform-version: '24.04'
      install-svgbob: true

  build-windows:
    uses: ./.github/workflows/build-targets-template.yml
    with:
      build-targets: 'sandcastle_exe'
      test-targets: 'run_sandcastle_tests'
      artifact-name: 'kanagawa-windows-sandcastle-${{ github.sha }}'
      artifact-path: 'build-ci/dist/**'
      cmake-build-type: 'RelWithDebInfo'
      runs-on: 'windows-2022'
      boost-platform-version: '2022'
      install-svgbob: true

  build-macos:
    uses: ./.github/workflows/build-targets-template.yml
    with:
      build-targets: 'sandcastle_exe'
      test-targets: 'run_sandcastle_tests'
      artifact-name: 'kanagawa-macos-sandcastle-${{ github.sha }}'
      artifact-path: 'build-ci/dist/**'
      cmake-build-type: 'RelWithDebInfo'
      runs-on: 'macos-15'
      boost-platform-version: '15'
      install-svgbob: true
